### ISSUE TITLE
Not working in ST3

### ISSUE THREAD

**Issue by lmartins** [vitorbritto/sublime-devdocs#1]
Hi,

Just installed using Package Control, the plugin is shown as installed but the option to show docs isn't available in search by input. 
In the Search by Selection the option is visible, but not available (greyed out) either with text selected and unselected.

Would be nice to search by selection with keyboard shortcut.

Cheers.

**Comment by lmartins** [comment]
Btw, this is what it shows on the menu entry, no matter what I have selected on the editor.
![screenshot 2013-08-22 09 06 42](https://f.cloud.github.com/assets/151981/1007217/0694d8cc-0b02-11e3-9e95-02f4d5324d05.png)

**Comment by vitorbritto** [comment]
Get latest :)
