### ISSUE TITLE
Shortcut already taken

### ISSUE THREAD

**Issue by nicolashohm** [vitorbritto/sublime-devdocs#3]
pls check the keybinding, ctrl + shift + d is already used by ST for duplicating lines.

**Comment by chid** [comment]
You can just change the Default (OS).sublime-keymap file to whatever you wish.

**Comment by manuhabitela** [comment]
Yeah we can change it but it's usually better if a plugin doesn't override a default shortcut. 

And in that case, `ctrl + shift + d` is a shortcut usually often used so it would be cool to change the plugin's default shortcut instead of having people change it by themselves.

**Comment by chid** [comment]
Sounds reasonable, what would be a good alternative?

**Comment by manuhabitela** [comment]
I use `ctrl + shift + ,` since a while for this. I actually prefer when plugins don't provide any default shortcuts because then I'm sure it doesn't override anything, but whatever ;)

**Comment by vitorbritto** [comment]
Hi guys, apologies for the delay. I think it's a good approach to remove the default shortcut. Let the user make her own decision. It's fine for me.
